name: Test

on:
  push:
  
jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          
          ./docker-test.sh
          cat result.log >> $GITHUB_STEP_SUMMARY